---
- name: Deploy docker compose
  hosts: all
  become: true
  tasks:
    - name: Git update lgtv-api-proxy repo
      ansible.builtin.git:
        repo: "https://github.com/bodav/lgtv-api-proxy.git"
        dest: /srv/lgtv-api-proxy
        force: true
      register: repo

    - name: Docker compose down
      ansible.builtin.shell: "docker compose -f /srv/lgtv-api-proxy/docker-compose.yml down --remove-orphans"
      when: repo.changed

    # - name: Docker compose pull
    #   ansible.builtin.shell: "docker compose -f /srv/lgtv-api-proxy/docker-compose.yml pull"

    - name: Docker compose up
      ansible.builtin.shell: "docker compose -f /srv/lgtv-api-proxy/docker-compose.yml up -d"
      when: repo.changed
